### ISSUE TITLE
[QA] 메인 페이지

### ISSUE THREAD

**Issue by 4anghyeon** [j-yesung/magic-pos#149]
1. 꼼꼼한 매출 분석까지 도와드려요
    - 스크롤시 아래에서 위로 올라올 때는 애니메이션 안 넣을 수 있는지?

2. 지금 헤더에 아무런 기능이 없는데 차라리 빼고 로고를 가운데 박는게 어떤지? (디자인)
<img width="1411" alt="image-20240119102315537" src="https://github.com/j-yesung/magic-pos/assets/64076628/16569809-ae58-4aa9-957e-42f928e15f28">

- [x] 로그인 안되어있을 경우 시작하기 버튼시 로그인 화면으로 이동
- [x] 로그인 후 로그인 버튼이 보이는 문제
- [x] 더미데이터 행간 조절

**Comment by j-yesung** [comment]
1번 수정 완료
2번은 디자이너님이랑 얘기를 해봐야 할 것 같습니다.
