### ISSUE TITLE
[QA] 회원가입 

### ISSUE THREAD

**Issue by 4anghyeon** [j-yesung/magic-pos#150]
1. 대소문자/특수문자 포함 8~16자리라 써있는데 규칙 안지켜도 회원가입 버튼이 활성화됨 (가입이 되진않음)
2. 단순히 8자리만 (aaaaaaaa) 채워도 가입이됨, 대소문자/특수문자 처리가 안되어있는 듯 함

**Comment by j-yesung** [comment]
수정 완료 (PR 예정)
