### ISSUE TITLE
hooks 폴더 분리 작업

### ISSUE THREAD

**Issue by 4anghyeon** [j-yesung/magic-pos#257]
## 설명
- hooks 폴더를 더 세분화 해서 구분합니다.

## To Do
- tanstack query를 위한 hook은 query 폴더 밑으로 이동합니다.
- 그 외 비즈니스 로직을 포함하는 hook은 service 폴더 밑으로 이동합니다.

**Comment by j-yesung** [comment]
- auth
- store
- useObserver

...SUCCESS

**Comment by tjdsksro90** [comment]
- category
- menu-item

옮겼습니다
