### ISSUE TITLE
공휴일 API 기능 

### ISSUE THREAD

**Issue by lunaxislu** [j-yesung/magic-pos#84]
## 설명
- 공휴일 API 기능을 calendar에 더하기

## To Do
- 공휴일 API기능 calendar component에 접목 시키기

## 비고
- 기타 사항

**Comment by 4anghyeon** [comment]
공휴일 API를 불러올 경우 CSR이 아닌 (ISR 혹은 SSG) + CSR로 불러오는 것이 좋을 것 같습니다..!?

서버에서는 공휴일 데이터를 불러옴 (ISR시 revalidate는... 1년!?, 공휴일 정보가 바뀔일은 거의 없기에....)
클라이언트에서는 매출 정보를 불러옴
